services:
  php:
    container_name: php
    build:
      context: ../
      dockerfile: server/php/Dockerfile
    volumes:
      - ../src:/var/www
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ../src/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - ./.env
    depends_on:
      - php
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    env_file:
      - ./.env
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
